name: CI
on:
  push:
    branches:
      - main
jobs:
              
  docker:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: test
        run: |
        
          set -x
          
          for script in *.py
            do
              dos2unix ${script}
              python ${script}
            done
